name: pypulseq
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - numpy=1.23.5
  - matplotlib=3.6.2
  - scipy=1.9.3
  - simple-parsing=0.0.21
  - tqdm=4.64.1
  - numba=0.56.4
  - pathtools=0.1.2
  - pip
  - pandas=1.5.2
